name: Build Develop

on:
  push:
    branches:
      - develop
      - feature/ci
    tags:
      - 'v*'

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-build-${{ hashFiles('gradlew') }}
        
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - run: ./gradlew assembleDebug

      - run: ./gradlew assembleRelease
        
      - run: cp app/build/outputs/apk/release/app-release-unsigned.apk badradio.apk

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: badradio.apk
