name: Unit Tests Develop

on:
  push:
    branches:
      - develop
    tags:
      - 'v*'

jobs:
  build:
    name: Test Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
          
      - run: ./gradlew test
