name: Unit Tests Develop

on:
  push:
    branches:
      - develop
    tags:
      - 'v*'
  schedule:
    - cron: '0 5 * * 3'

jobs:
  build:
    name: Test Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-test-${{ hashFiles('gradlew') }}
        
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
          
      - run: ./gradlew test
